# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.cache/wt [current_project]
set_property parent.project_path D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/imports/Downloads/convert/wallpaper1.mem
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/imports/Downloads/convertt/screen_1.mem
  {D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/imports/Downloads/lockscreen images/correct_password.mem}
  {D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/imports/Downloads/lockscreen images/wrong/wrong_password.mem}
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/imports/Downloads/speaker_screen/speaker_screen.mem
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/imports/Downloads/tic_tac_toe_screen/tic_tac_toe_screen.mem
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/imports/Downloads/ball_screen/ball_screen.mem
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/imports/Downloads/new_welcome/new_welcome.mem
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/imports/Downloads/audio_visu/audio.mem
  {C:/Users/Anitej Datta/OneDrive - National University of Singapore/Downloads/audio_new/audio_new.mem}
  {C:/Users/Anitej Datta/OneDrive - National University of Singapore/Downloads/ball_new/ball_new.mem}
  {C:/Users/Anitej Datta/OneDrive - National University of Singapore/Downloads/speaker_screen_new/speaker_screen_new.mem}
  {C:/Users/Anitej Datta/OneDrive - National University of Singapore/Downloads/new_tic_tac_toe/tic_new.mem}
  {C:/Users/Anitej Datta/OneDrive - National University of Singapore/Downloads/car_final/car_final.mem}
}
read_verilog -library xil_defaultlib {
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/Audio_Capture.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/Audio_Visualize_App.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/Catch_Ball_App.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/imports/EE2026vivado/TTTEditedFinal.xpr/ProjectTicTacToe/ProjectTicTacToe.srcs/sources_1/new/Clk6p25.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/Home_Screen_App.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/imports/EE2026vivado/TTTEditedFinal.xpr/ProjectTicTacToe/ProjectTicTacToe.srcs/sources_1/new/Initialisation.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/LEDS.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/Lock_Screen_App.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/Music_App.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/Oled_C.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/imports/EE2026vivado/TTTEditedFinal.xpr/ProjectTicTacToe/ProjectTicTacToe.srcs/sources_1/new/Oled_Display.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/SEG_CTRL_FINAL.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/imports/EE2026vivado/TTTEditedFinal.xpr/ProjectTicTacToe/ProjectTicTacToe.srcs/sources_1/new/TTT.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/a_440hz.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/app_fsm.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/app_select.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/app_select_1.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/app_select_2.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/app_select_3.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/app_select_4.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/app_select_5.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/b_494hz.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/ball_game.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/imports/EE2026vivado/Week_9_A0284708U.xpr/improvement_project/improvement_project.srcs/sources_1/new/bar_height.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/button_fsm.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/cH_523hz.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/c_256hz.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/clock_chosen.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/coordniate.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/dH_587hz.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/debouncer.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/debouncer_clk200ms.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/debouncer_v1.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/detect_press.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/dff.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/dsharp.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/eH_659hz.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/e_329hz.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/fH_698hz.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/f_349hz.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/imports/EE2026vivado/TTTEditedFinal.xpr/ProjectTicTacToe/ProjectTicTacToe.srcs/sources_1/new/flexi_clk.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/gH_784hz.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/gS_415hz.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/g_392hz.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/home_button_fsm.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/improved_clock.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/led_blinker.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/led_switcher.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/imports/EE2026vivado/Week_9_A0284708U.xpr/improvement_project/improvement_project.srcs/sources_1/new/mic_abs.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/note.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/password_check.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/imports/EE2026vivado/TTTEditedFinal.xpr/ProjectTicTacToe/ProjectTicTacToe.srcs/sources_1/new/pix_convert.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/screen_correct_psw.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/screen_locked.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/screen_wrong_psw.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/segment_control_music.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/song_fur_elise.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/song_imperial_march.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/song_never_gonna_give_you_up.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/song_ode_to_joy.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/song_state_update.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/speaker.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/state_counter_16.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/sw_change.v
  D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/sources_1/new/Top_Student.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/constrs_1/new/basys3.xdc
set_property used_in_implementation false [get_files D:/EE2026vivado/project_final_workingon.xpr/project_ver2/project_ver2.srcs/constrs_1/new/basys3.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top_Student -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Student.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Student_utilization_synth.rpt -pb Top_Student_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
